### ISSUE TITLE
Dynamic shadows in rearview mirror

### ISSUE THREAD

**Issue by NicolasFLM** [AeroWidescreen/NFSMWHDReflections#3] opened 2019-06-30 22:04 UTC
Hey man, first thanks for this great mod, now the rearview mirror actually look's good. I noticed that normally dynamic shadows don't appear in the rearview mirror, but in this particular tunel some shadows actually seems to appear even though they are completely broken. So now i'm wondering if it's possible to restore and fix the shadows to appear in the rearview mirror like you did with the others effects. 
![Shadows](https://user-images.githubusercontent.com/26664934/60402724-c88bfe80-9b69-11e9-998b-ba7cc14a893d.png)

**Comment by AeroWidescreen** [comment] 2019-07-30 07:56
It's an interesting glitch, isn't it? I can get the same thing to happen in the main world by disabling almost all of the dynamic shadow code. I'm more concerned about what effect this has on performance if the game is trying to render them in the mirror _and_ vehicle reflections.

As for enabling them, I doubt the game could even handle it. This glitch is not proof that it could. Like I said, it's missing almost everything needed for dynamic shadows. You're basically seeing a small section of the world being darkened as a side-effect of the shader restoration. This is why they don't move and remain completely unaffected by shadow resolution.

**Comment by vjadid** [comment] 2019-08-27 04:03
I can see shadows in mirror if "Shadow detail" in video settings is set to either none or half ( out of 3 levels to choose from). If I max out shadow detail the shadows in mirror disappear. 
Also not all shadows are visible, for some objects it is still missing.
I'm using 13AG widescreen fix to improve shadow resolution.

![shadows in mirror](https://user-images.githubusercontent.com/29530546/63740164-98cd4e80-c8ad-11e9-8e63-80ff99f1760e.png)
![shadows setting](https://user-images.githubusercontent.com/29530546/63740165-9965e500-c8ad-11e9-8042-298c97657cff.PNG)

**Comment by kazuya44** [comment] 2019-09-30 09:15
@vjadid 
thats because reducing the shadow option changes some shadows to fake (or painted ? ) and those are what can be usually reflected in the mirror.

I do notice another glitch though where sometimes when starting the game, the car has a super shinny effect and the reflections on it become glitched unless I restart the game untill it corrects

**Comment by AeroWidescreen** [comment] 2019-10-01 06:34
The shadow issue should be solved now. Wait for the next update.

![RVM Shadow](https://i.imgur.com/RPSik8b.png)

In case anyone asks me about this: the line you see here is not a shadow. It has something to do with the lighting for the tunnel and it's not a problem caused by HD Reflections or any other mod.

![RVM Tunnel](https://i.imgur.com/X4N5a5J.png)

**Comment by kazuya-555** [comment] 2019-10-01 12:00
another thing, in settings for mirror it says 1= lights and 2 = particles, is 2=both or just particles ?

**Comment by AeroWidescreen** [comment] 2019-10-01 19:24
Both.

**Comment by vjadid** [comment] 2019-10-02 08:04
> 
> 
> The shadow issue should be solved now. Wait for the next update.
> 
> ![RVM Shadow](https://camo.githubusercontent.com/087580ca579052c1b74af0909cbf2338de9264e7/68747470733a2f2f692e696d6775722e636f6d2f525053696b38622e706e67)
> 
> In case anyone asks me about this: the line you see here is not a shadow. It has something to do with the lighting for the tunnel and it's not a problem caused by HD Reflections or any other mod.
> 
> ![RVM Tunnel](https://camo.githubusercontent.com/c204b22ca9840c8e7d14b4627da119e8a05c1527/68747470733a2f2f692e696d6775722e636f6d2f58344e3561354a2e706e67)

Your screenshots always look so good, what all mods are you using ?

**Comment by AeroWidescreen** [comment] 2019-10-12 00:28
The update is available now. Let me know if you guys still experience problems. I'm closing this for now.

> Your screenshots always look so good, what all mods are you using ?

[NFSMW HUD Resizer](https://nfsmods.xyz/mod/1204)
[Xbox 360 Stuff Pack](https://nfsmods.xyz/mod/1200)
[Xbox 360 Platform Textures](https://nfsmods.xyz/mod/674)
[Xbox 360 Vinyls](https://nfs-tools.blogspot.com/2018/09/nfs-most-wanted-high-quality-vinyls-v10.html)

**Closed by AeroWidescreen** 2019-10-12 00:28 UTC
